###

# Delete vehicle entry
DELETE http://localhost:5001/api/vehicles/5f4a9db8bab7a60db9e7fe6c
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlcHN1a2thIiwiaWQiOiI1ZmFmYmMyNWFkMWNlNDNhYThkNWUzOGMiLCJpYXQiOjE2MDYyMzcwNTB9.YHdgtDns5pN3jpZ4ByQKHLTA9BX33VIUNv4zWdoyfuk