name: Bump package.json version

on:
  push:
    branches: [master]

jobs:

  bump_package_json_version:

    runs-on: ubuntu-18.04
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name:  'Automated Version Bump'
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGEJSON_DIR:  'fuel-tracker-be'
        with:
          skip-tag: 'true'
          default: patch